-- GENERATED by `npm run db:fingerprint`. Do not edit by hand.
--
-- Checks a Restaurant Direct project against the baseline in
-- supabase/migrations. Read-only. Zero rows back means it matches exactly.
-- Any row names the object that is missing, extra, or defined differently.

with actual as (
  with
  our_functions as (
    select p.oid, (p.proname::text || '(' || pg_get_function_identity_arguments(p.oid) || ')') as name
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.prokind = 'f'
      and p.proname <> 'rls_auto_enable'
      and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
  ),
  our_tables as (
    select c.oid, c.relname::text as relname
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relkind = 'r'
  ),
  rows as (
    -- Every name is text: Postgres's own name type is capped at 63 bytes and
    -- would silently truncate long function signatures into duplicates.
    select 'table'::text as kind, t.relname::text as name, md5(concat_ws('|',
      (select string_agg(format('%I %s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
          case when a.attnotnull then ' not null' else '' end,
          case when d.adbin is not null then ' default ' || pg_get_expr(d.adbin, d.adrelid) else '' end), ',' order by a.attnum)
       from pg_attribute a left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
       where a.attrelid = t.oid and a.attnum > 0 and not a.attisdropped),
      (select string_agg(format('%s %s', con.conname, pg_get_constraintdef(con.oid)), ',' order by con.conname)
       from pg_constraint con where con.conrelid = t.oid),
      (select string_agg(pg_get_indexdef(i.indexrelid), ',' order by pg_get_indexdef(i.indexrelid))
       from pg_index i where i.indrelid = t.oid),
      (select relrowsecurity::text from pg_class where oid = t.oid)
    )) as fingerprint
    from our_tables t
  
    union all
    select 'function', f.name, md5(pg_get_functiondef(f.oid)) from our_functions f
  
    union all
    select 'trigger', c.relname::text || '.' || tg.tgname::text, md5(pg_get_triggerdef(tg.oid))
    from pg_trigger tg
    join pg_class c on c.oid = tg.tgrelid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and not tg.tgisinternal
  
    union all
    select 'policy', tablename::text || '.' || policyname::text, md5(concat_ws('|', permissive, cmd,
      array_to_string(roles, ','), qual, with_check))
    from pg_policies
    where schemaname = 'public'
  
    union all
    select 'table_grant', t.relname || ' ' || r.rolname, md5(concat_ws(',',
      case when has_table_privilege(r.rolname, t.oid, 'SELECT') then 'select' end,
      case when has_table_privilege(r.rolname, t.oid, 'INSERT') then 'insert' end,
      case when has_table_privilege(r.rolname, t.oid, 'UPDATE') then 'update' end,
      case when has_table_privilege(r.rolname, t.oid, 'DELETE') then 'delete' end,
      case when has_table_privilege(r.rolname, t.oid, 'TRUNCATE') then 'truncate' end,
      case when has_table_privilege(r.rolname, t.oid, 'REFERENCES') then 'references' end,
      case when has_table_privilege(r.rolname, t.oid, 'TRIGGER') then 'trigger' end))
    from our_tables t
    cross join (values ('anon'), ('authenticated')) as r(rolname)
  
    union all
    select 'function_exec', f.name || ' ' || r.rolname,
      md5(has_function_privilege(r.rolname, f.oid, 'EXECUTE')::text)
    from our_functions f
    cross join (values ('anon'), ('authenticated')) as r(rolname)
  )
  select kind, name, fingerprint from rows
),
expected(kind, name, fingerprint) as (
  values
    ('function', 'bookings_upsert_customer()', 'e52ac4d5c2bb9d4624757a420bc4f0fb'),
    ('function', 'create_order(p_order_no text, p_customer_name text, p_email text, p_phone text, p_order_type text, p_table_number text, p_delivery_address text, p_delivery_notes text, p_requested_time timestamp with time zone, p_total numeric, p_marketing_consent boolean, p_items jsonb)', '6a27156c41733fad4f70a1fde7cb65fe'),
    ('function', 'enforce_booking_status_transition()', '815fe4b71941d2cf1603b9abd4adb69f'),
    ('function', 'enforce_order_status_transition()', 'd3373bcf1e38226138d1a32f3a079869'),
    ('function', 'is_staff()', '317765192237ae8c8e190cbd7a1f3f84'),
    ('function', 'lookup_request(p_reference text, p_contact text)', '1e99e9f6977dfea442112126b19e3161'),
    ('function', 'normalise_phone(p_phone text)', 'd7b6e4368f985baea90ad9036186a915'),
    ('function', 'notify_booking_webhook()', '085ae719f76d07db3536999fb9b91267'),
    ('function', 'orders_upsert_customer()', 'ee484d885ce2e38c7b046b04707c58b1'),
    ('function', 'send_review_requests()', '7bfa133060d19eb21b6811e9333f5b63'),
    ('function', 'set_completed_at()', '2dca1692b45d6e9ee606598392247346'),
    ('function', 'set_updated_at()', '63f977f8e2e3db6a119fcbe248bf3314'),
    ('function', 'setting(p_key text)', '314d595931a9b4a27372629c42a228ef'),
    ('function', 'throttle_booking_inserts()', 'a00d958df435f8c392f4fc41dc64f39f'),
    ('function', 'upsert_customer(p_name text, p_email text, p_phone text, p_marketing_consent boolean)', '288c30c8fc57995bd2f174def7b54a39'),
    ('function_exec', 'bookings_upsert_customer() anon', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'bookings_upsert_customer() authenticated', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'create_order(p_order_no text, p_customer_name text, p_email text, p_phone text, p_order_type text, p_table_number text, p_delivery_address text, p_delivery_notes text, p_requested_time timestamp with time zone, p_total numeric, p_marketing_consent boolean, p_items jsonb) anon', 'b326b5062b2f0e69046810717534cb09'),
    ('function_exec', 'create_order(p_order_no text, p_customer_name text, p_email text, p_phone text, p_order_type text, p_table_number text, p_delivery_address text, p_delivery_notes text, p_requested_time timestamp with time zone, p_total numeric, p_marketing_consent boolean, p_items jsonb) authenticated', 'b326b5062b2f0e69046810717534cb09'),
    ('function_exec', 'enforce_booking_status_transition() anon', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'enforce_booking_status_transition() authenticated', 'b326b5062b2f0e69046810717534cb09'),
    ('function_exec', 'enforce_order_status_transition() anon', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'enforce_order_status_transition() authenticated', 'b326b5062b2f0e69046810717534cb09'),
    ('function_exec', 'is_staff() anon', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'is_staff() authenticated', 'b326b5062b2f0e69046810717534cb09'),
    ('function_exec', 'lookup_request(p_reference text, p_contact text) anon', 'b326b5062b2f0e69046810717534cb09'),
    ('function_exec', 'lookup_request(p_reference text, p_contact text) authenticated', 'b326b5062b2f0e69046810717534cb09'),
    ('function_exec', 'normalise_phone(p_phone text) anon', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'normalise_phone(p_phone text) authenticated', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'notify_booking_webhook() anon', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'notify_booking_webhook() authenticated', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'orders_upsert_customer() anon', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'orders_upsert_customer() authenticated', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'send_review_requests() anon', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'send_review_requests() authenticated', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'set_completed_at() anon', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'set_completed_at() authenticated', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'set_updated_at() anon', 'b326b5062b2f0e69046810717534cb09'),
    ('function_exec', 'set_updated_at() authenticated', 'b326b5062b2f0e69046810717534cb09'),
    ('function_exec', 'setting(p_key text) anon', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'setting(p_key text) authenticated', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'throttle_booking_inserts() anon', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'throttle_booking_inserts() authenticated', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'upsert_customer(p_name text, p_email text, p_phone text, p_marketing_consent boolean) anon', '68934a3e9455fa72420237eb05902327'),
    ('function_exec', 'upsert_customer(p_name text, p_email text, p_phone text, p_marketing_consent boolean) authenticated', '68934a3e9455fa72420237eb05902327'),
    ('policy', 'bookings.public can insert bookings', '2602f7a561f072b920f07ec917d42b1c'),
    ('policy', 'bookings.staff can read bookings', '01b0c0ed877988322b8cd32d4ff2d3b6'),
    ('policy', 'bookings.staff can update bookings', 'a3510387d785799ffe700d98c38d21ee'),
    ('policy', 'customers.staff can read customers', '01b0c0ed877988322b8cd32d4ff2d3b6'),
    ('policy', 'notification_log.staff can read notification_log', '01b0c0ed877988322b8cd32d4ff2d3b6'),
    ('policy', 'order_items.staff can read order_items', '01b0c0ed877988322b8cd32d4ff2d3b6'),
    ('policy', 'orders.staff can read orders', '01b0c0ed877988322b8cd32d4ff2d3b6'),
    ('policy', 'orders.staff can update orders', 'a3510387d785799ffe700d98c38d21ee'),
    ('policy', 'staff.staff can read staff', '01b0c0ed877988322b8cd32d4ff2d3b6'),
    ('table', 'app_settings', 'fbfc466c6ecb0af68bdc8c66ab946931'),
    ('table', 'bookings', '180c2babc70504a3bbb011af7ef97d9a'),
    ('table', 'customers', '1c7e8f347e7624070a4e1fc79284126c'),
    ('table', 'menu_items', '5b50734798b340b7394302697c15cc8d'),
    ('table', 'notification_log', 'd04ff95301162177fc65c5920a2c9a0a'),
    ('table', 'order_items', '7719f017abe1400781d13677078ada93'),
    ('table', 'orders', 'c16843b9b4a3fce3d6d1e1192b7e9a4d'),
    ('table', 'staff', 'e45c9fe6a7adde50cb796b61f1ddded9'),
    ('table_grant', 'app_settings anon', 'd41d8cd98f00b204e9800998ecf8427e'),
    ('table_grant', 'app_settings authenticated', 'd41d8cd98f00b204e9800998ecf8427e'),
    ('table_grant', 'bookings anon', 'e0df5f3dfd2650ae5be9993434e2b2c0'),
    ('table_grant', 'bookings authenticated', '4649341c949f5788e8074f3145221634'),
    ('table_grant', 'customers anon', 'd41d8cd98f00b204e9800998ecf8427e'),
    ('table_grant', 'customers authenticated', '85fe4c43704bc5b95d3da94654df1466'),
    ('table_grant', 'menu_items anon', 'd41d8cd98f00b204e9800998ecf8427e'),
    ('table_grant', 'menu_items authenticated', 'd41d8cd98f00b204e9800998ecf8427e'),
    ('table_grant', 'notification_log anon', 'd41d8cd98f00b204e9800998ecf8427e'),
    ('table_grant', 'notification_log authenticated', '99938282f04071859941e18f16efcf42'),
    ('table_grant', 'order_items anon', 'd41d8cd98f00b204e9800998ecf8427e'),
    ('table_grant', 'order_items authenticated', '4649341c949f5788e8074f3145221634'),
    ('table_grant', 'orders anon', 'd41d8cd98f00b204e9800998ecf8427e'),
    ('table_grant', 'orders authenticated', '4649341c949f5788e8074f3145221634'),
    ('table_grant', 'staff anon', 'd41d8cd98f00b204e9800998ecf8427e'),
    ('table_grant', 'staff authenticated', '99938282f04071859941e18f16efcf42'),
    ('trigger', 'bookings.bookings_enforce_status', '44fe2a4089a0ca2efa0bac3b490d1edd'),
    ('trigger', 'bookings.bookings_notify_webhook', '2eec16e574f586d2a08417246b1f7f6c'),
    ('trigger', 'bookings.bookings_set_customer', 'b65a128bb5af392a21ab91dc875b2716'),
    ('trigger', 'bookings.bookings_set_updated_at', 'de44fc0684853516497a8b7b5e3dbb8a'),
    ('trigger', 'bookings.bookings_throttle', '36f8392f38202473055521a054c4afd1'),
    ('trigger', 'orders.orders_enforce_status', '5449bf721cfe7e05b15fae8495a7f01e'),
    ('trigger', 'orders.orders_set_completed_at', '6359a6638ad0429601d7d2f5012dc3f9'),
    ('trigger', 'orders.orders_set_customer', '2dfb6318477fa4a32987f78fdb43e719'),
    ('trigger', 'orders.orders_set_updated_at', 'b8d42c9e1eca5539c98563bb4628b440')
)
select coalesce(e.kind, a.kind) as kind,
       coalesce(e.name, a.name) as name,
       case when a.name is null then 'missing from this project'
            when e.name is null then 'not in the baseline'
            else 'defined differently' end as problem
from expected e
full outer join actual a on a.kind = e.kind and a.name = e.name
where a.fingerprint is distinct from e.fingerprint
order by 1, 2;
