-- GENERATED by `npm run menu:sql` from the jimmys tenant config. Do not edit by hand.
-- Apply to the tenant's database BEFORE deploying a menu or price change: until
-- it is applied, create_order refuses the new prices.
with upserted as (
  insert into public.menu_items (name, category, price, available_until)
  values
    ('Breakfast Bun', 'Breakfast', 60.00, '12:00'),
    ('Breakfast Burger', 'Breakfast', 95.00, '12:00'),
    ('Jimmy''s Breakfast', 'Breakfast', 70.00, '12:00'),
    ('Avo on Toast', 'Breakfast', 60.00, '12:00'),
    ('Omelette', 'Breakfast', 60.00, '12:00'),
    ('Carb Clever Breakfast', 'Breakfast', 60.00, '12:00'),
    ('Beef Burger', 'Burgers', 90.00, null),
    ('Chicken Burger', 'Burgers', 90.00, null),
    ('Smash Burger', 'Burgers', 100.00, null),
    ('Pizza Burger', 'Burgers', 105.00, null),
    ('Gourmet Burger', 'Burgers', 130.00, null),
    ('Nacho Burger', 'Burgers', 130.00, null),
    ('Russian & Chips', 'Small Plates', 55.00, null),
    ('Jalapeño Poppers', 'Small Plates', 65.00, null),
    ('Nachos', 'Small Plates', 90.00, null),
    ('Steak Strips', 'Small Plates', 80.00, null),
    ('Loaded Fries', 'Small Plates', 60.00, null),
    ('Plate of Fries', 'Small Plates', 45.00, null),
    ('Plate of Onion Rings', 'Small Plates', 35.00, null),
    ('Meatballs', 'Small Plates', 60.00, null),
    ('Warrior Platter', 'Platters', 350.00, null),
    ('Snack Platter', 'Platters', 250.00, null),
    ('200g Rump Steak', 'Steaks', 110.00, null),
    ('300g Rump Steak', 'Steaks', 140.00, null),
    ('200g Jalapeño Steak', 'Steaks', 130.00, null),
    ('300g Jalapeño Steak', 'Steaks', 160.00, null),
    ('250g Fillet Steak', 'Steaks', 140.00, null),
    ('Extra Sauce', 'Steaks', 25.00, null),
    ('Chicken Wings', 'Chicken Meals', 90.00, null),
    ('Chicken Strips', 'Chicken Meals', 70.00, null),
    ('Chicken Schnitzel', 'Chicken Meals', 95.00, null),
    ('Chicken Mayo', 'Toasted Sandwiches', 70.00, null),
    ('Bacon & Cheese', 'Toasted Sandwiches', 65.00, null),
    ('Cheese & Tomato', 'Toasted Sandwiches', 50.00, null),
    ('Greek Salad', 'Salads', 55.00, null),
    ('Jimmy''s Salad', 'Salads', 80.00, null),
    ('Burger Salad', 'Salads', 90.00, null),
    ('Chicken Salad', 'Salads', 70.00, null),
    ('Steak Salad', 'Salads', 85.00, null),
    ('Cake of the Day', 'Desserts', 45.00, null),
    ('Ice Cream & Chocolate Sauce', 'Desserts', 30.00, null),
    ('Affogato', 'Desserts', 45.00, null),
    ('Coke', 'Non-alcoholic drinks', 25.00, null),
    ('Coke Zero', 'Non-alcoholic drinks', 25.00, null),
    ('Sprite', 'Non-alcoholic drinks', 25.00, null),
    ('Fanta Orange', 'Non-alcoholic drinks', 25.00, null),
    ('Still Water', 'Non-alcoholic drinks', 18.00, null),
    ('Sparkling Water', 'Non-alcoholic drinks', 22.00, null),
    ('Appletiser', 'Non-alcoholic drinks', 30.00, null),
    ('Heineken 0.0', 'Non-alcoholic drinks', 30.00, null)
  on conflict (name) do update set
    category = excluded.category,
    price = excluded.price,
    available_until = excluded.available_until,
    available = true,
    updated_at = now()
  returning name
)
update public.menu_items
set available = false, updated_at = now()
where available and name not in (select name from upserted);
