-- GENERATED by `npm run tenant:sql -- jimmys` from supabase/tenants/jimmys.json
-- and src/tenants/jimmys/config.ts. Do not edit by hand.
--
-- Safe to run more than once. Apply after the baseline migration.

insert into public.app_settings (key, value, description)
values
  ('timezone', 'Africa/Johannesburg', 'IANA zone for restaurant-local rules such as breakfast cut-off'),
  ('phone.country_code', '27', 'Country code used to match local and international forms of one phone number'),
  ('webhook.order', 'https://dockerfile-1n82.onrender.com/webhook/jimmys-order', 'n8n webhook for new order notifications'),
  ('webhook.booking', 'https://dockerfile-1n82.onrender.com/webhook/jimmys-booking', 'n8n webhook for new booking notifications'),
  ('webhook.review', 'https://dockerfile-1n82.onrender.com/webhook/jimmys-review-request', 'n8n webhook for review request emails')
on conflict (key) do update set
  value = excluded.value,
  description = excluded.description,
  updated_at = now();

-- One review job per project, whatever it was named before (20:00 Africa/Johannesburg is 0 18 * * * UTC).
select cron.unschedule(jobid) from cron.job where command = 'select public.send_review_requests()';
select cron.schedule('restaurant-direct-review-requests', '0 18 * * *', 'select public.send_review_requests()');
