import type { MenuCategory, MenuItem } from '../config/types';
import { fromMinor, toMinor } from '../domain/money';

/**
 * Everything a customer can put in an online order, with the price the server
 * will charge.
 *
 * One definition feeds both the order page and the database price list
 * (`npm run menu:sql`), so the two cannot quietly disagree about what is on
 * sale or what it costs.
 */
export interface OrderableItem {
  name: string;
  category: string;
  /** Human decimal, as the database stores it. */
  price: number;
  /** 24h "HH:MM" after which the item cannot be requested, e.g. breakfast until 12:00. */
  availableUntil: string | null;
}

export interface OrderableCategory extends MenuCategory {
  items: MenuItem[];
}

export function orderableCategories(
  menuCategories: MenuCategory[],
  softDrinks: { label: string; note: string; items: MenuItem[] },
): OrderableCategory[] {
  return [...menuCategories, { name: softDrinks.label, note: softDrinks.note, items: softDrinks.items }];
}

/** Priced items only: an item with no price cannot be added to a cart. */
export function orderableItems(categories: OrderableCategory[]): OrderableItem[] {
  return categories.flatMap((category) =>
    category.items
      .filter((item) => typeof item.price === 'number' && item.price > 0)
      .map((item) => ({
        name: item.name,
        category: category.name,
        // Through minor units, exactly as the cart does, so a price like 25.505
        // rounds the same way on both sides instead of every order for it being refused.
        price: fromMinor(toMinor(item.price as number)),
        availableUntil: category.availableUntil ?? null,
      })),
  );
}

const literal = (value: string | null): string => (value === null ? 'null' : `'${value.replace(/'/g, "''")}'`);

/**
 * SQL that makes `public.menu_items` match the config exactly: upserts every
 * orderable item and marks anything no longer in the config unavailable, so a
 * dish taken off the menu stops being orderable instead of lingering.
 */
export function menuItemsSql(items: OrderableItem[], tenant: string): string {
  const names = new Set<string>();
  for (const item of items) {
    if (names.has(item.name)) throw new Error(`Duplicate orderable item name "${item.name}": the server prices items by name`);
    names.add(item.name);
  }

  const rows = items
    .map((item) => `  (${literal(item.name)}, ${literal(item.category)}, ${item.price.toFixed(2)}, ${literal(item.availableUntil)})`)
    .join(',\n');

  const header = `-- GENERATED by \`npm run menu:sql\` from the ${tenant} tenant config. Do not edit by hand.
-- Apply to the tenant's database BEFORE deploying a menu or price change: until
-- it is applied, create_order refuses the new prices.\n`;

  if (!items.length) {
    return `${header}update public.menu_items
set available = false, updated_at = now()
where available;\n`;
  }

  // One statement, so it is atomic however it is run (psql autocommit, the
  // Supabase SQL editor, an MCP call). The UPDATE only touches names the INSERT
  // did not, so no row is modified twice.
  return `${header}with upserted as (
  insert into public.menu_items (name, category, price, available_until)
  values
${rows.replace(/^/gm, '  ')}
  on conflict (name) do update set
    category = excluded.category,
    price = excluded.price,
    available_until = excluded.available_until,
    available = true,
    updated_at = now()
  returning name
)
update public.menu_items
set available = false, updated_at = now()
where available and name not in (select name from upserted);
`;
}
